# Generated by Django 5.0.1 on 2024-01-19 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='demo',
        ),
    ]
