# Generated by Django 5.0.1 on 2024-01-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.DateTimeField(max_length=50)),
                ('last_name', models.DateTimeField(max_length=50)),
                ('email', models.DateTimeField(max_length=50)),
                ('phone', models.DateTimeField(max_length=50)),
                ('address', models.DateTimeField(max_length=50)),
                ('city', models.DateTimeField(max_length=50)),
                ('state', models.DateTimeField(max_length=50)),
                ('zipcode', models.DateTimeField(max_length=50)),
            ],
        ),
    ]
